name: changelog
changelogname: changelog
version: 1.3.4
description: Helps to write your CHANGELOG.md
author: office@mikemitterer.at
homepage: https://github.com/MikeMitterer/dart-git-help

environment:
  sdk: '>=1.0.0 <2.0.0'

# Add the bin/git-init.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  changelog:
  cl: changelog

dependencies:
  logging: any
  logging_handlers: any

  intl: any
  args: any
  validate: any
  browser_detect: any

  console_log_handler: any
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

dev_dependencies:
  unittest: any
