name: changelog
changelogname: changelog
version: 1.4.1
description: Helps to write your CHANGELOG.md
author: office@mikemitterer.at
homepage: https://github.com/MikeMitterer/dart-git-help

environment:
    sdk: ">=1.8.0 <2.0.0"

# Add the bin/git-init.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  changelog:
  cl: changelog

dependencies:
  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  intl: ^0.12.0
  args: ^0.13.0
  validate: ^1.0.0
  browser_detect: ^1.0.0

dev_dependencies:
  test: any
  grinder: any